config/routes.rb
Rails.application.routes.draw do
  resources :colaborators do
    member do
      get "preview"
    end

    collection do
      get 'search'
    end     
  end
   
  root "colaborators#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/colaborator.rb
# == Schema Information
#
# Table name: colaborators
#
#  id         :bigint           not null, primary key
#  name       :string
#  email      :string
#  direction  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Colaborator < ApplicationRecord
    validates :name, presence: true, length: { minimum: 2 }, uniqueness: true
    validates :email, presence: true
    validates :direction, presence: true

    include PgSearch::Model

    pg_search_scope :search_full_text, against: {
        email: 'A',
        id: 'B',
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/colaborators_controller.rb
class ColaboratorsController < ApplicationController
  before_action :set_colaborator, only: %i[ show edit update destroy ]
  
  # GET /colaborators or /colaborators.json
  def index
    @colaborator = Colaborator.new
    @pagy, @colaborators = pagy(Colaborator.all.order(:created_at => :desc))

    if params[:query_text].present?
      @colaborators = @colaborators.search_full_text(params[:query_text])
    end
  end

  # GET /colaborators/1 or /colaborators/1.json
  def show
  end

  # GET /colaborators/1/preview
  def preview
  end
 
  # GET /colaborators/search
  def search
  end
 

  # GET /colaborators/new
  def new
  end

  # GET /colaborators/1/edit
  def edit
  end

  # POST /colaborators or /colaborators.json
  def create
    @colaborator = Colaborator.new(colaborator_params)

    respond_to do |format|
      if @colaborator.save
        format.html { redirect_to colaborators_url, notice: "Colaborator was successfully created." }
        format.json { render :show, status: :created, location: @colaborator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @colaborator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colaborators/1 or /colaborators/1.json
  def update
    respond_to do |format|
      if @colaborator.update(colaborator_params)
        format.html { redirect_to colaborator_url(@colaborator), notice: "Se actualizo satisfactoriamente." }
        format.json { render :show, status: :ok, location: @colaborator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @colaborator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colaborators/1 or /colaborators/1.json
  def destroy
    @colaborator.destroy

    respond_to do |format|
      format.html { redirect_to colaborators_url, notice: "Colaborator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colaborator
      @colaborator = Colaborator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def colaborator_params
      params.require(:colaborator).permit(:name, :email, :direction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/colaborators_helper.rb
module ColaboratorsHelper
end

app/views/colaborators/_colaborator.html.erb
<div id="<%= dom_id colaborator %>">
  <p>
    <strong>Id:</strong>
    <%= colaborator.id %>
  </p>
  
  <p>
    <strong>Name:</strong>
    <%= colaborator.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= colaborator.email %>
  </p>

  <p>
    <strong>Direction:</strong>
    <%= colaborator.direction %>
  </p>

  <p>
    <strong>created_at:</strong>
    <%= colaborator.created_at %>
  </p>

  <p>
    <strong>updated_at:</strong>
    <%= colaborator.updated_at %>
  </p>
</div>

app/views/colaborators/_form.html.erb
<%= form_with(model: colaborator) do |form| %>
  <% if colaborator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(colaborator.errors.count, "error") %> prohibited this colaborator from being saved:</h2>

      <ul>
        <% colaborator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class: "form-label" %>
    <%= form.text_field :email, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :direction, class: "form-label" %>
    <%= form.text_field :direction, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/colaborators/edit.html.erb
<h1>Editing colaborator</h1>

<%= render "form", colaborator: @colaborator %>

<br>

<div>
  <%= link_to "Show this colaborator", @colaborator %> |
  <%= link_to "Back to colaborators", colaborators_path %>
</div>

app/views/colaborators/index.html.erb
<p style="color: green"><%= notice %></p>

<%= form_with url: colaborators_path, method: :get do |form| %>
  <%= form.text_field :query_text,
    placeholder: 'Query text',
    value: params[:query_text] %>
<% end %>

<hr>
<hr>

<h1>Colaborators</h1>

<%= render "form", colaborator: @colaborator %>

<%= link_to new_colaborator_path, class: "btn btn-light" do %>
  ➕ Add a new colaborator
<% end %>

<div id="colaborators">
  <% @colaborators.each do |colaborator| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= colaborator.name %></h5>
        <h6 class="card-subtitle mb-2 text-body-secondary"><%= colaborator.email %></h6>
        <p class="card-text"><%= colaborator.direction %></p>
        <%= link_to "Show this colaborator", colaborator, class: "card-link" %>
      </div>
    </div>
    <br>
  <% end %>
</div>

<%== pagy_bootstrap_nav(@pagy) %>

app/views/colaborators/new.html.erb
<h1>New colaborator</h1>

<%= render "form", colaborator: @colaborator %>

<br>

<div>
  <%= link_to "Back to colaborators", colaborators_path %>
</div>

app/views/colaborators/preview.html.erb
<h1>Vista preview como ruta miembro</h1>
<h2>Miembro de colección con ID:
<%=params[:id]%></h2>

app/views/colaborators/search.html.erb
<h1>Buscador de colaboradores</h1>

app/views/colaborators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @colaborator %>

<div>
  <%= link_to "Edit this colaborator", edit_colaborator_path(@colaborator) %> |
  <%= link_to "Back to colaborators", colaborators_path %>

  <%= button_to "Destroy this colaborator", @colaborator, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColaboradoresRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <main class="container">
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Colaborators", colaborators_path, class: "nav-link" %>
        </li>
        
      </ul>
      
    </div>
  </div>
</nav>